<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(NetLibVersion);</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>Valtuutus optional built-in hosted services (e.g. the tombstone reaper timer); $(Description)</Description>
        <PackageTags>$(PackageTags);hosting;backgroundservice</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Valtuutus.Data\Valtuutus.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    </ItemGroup>

</Project>
