on:
  push:
    branches:
      - main
      - dev

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: |
            10.x
            9.x
            8.x
            7.x
            6.x
      - name: Run Benchmarks
        run: |
          dotnet run -c Release --filter '*' --project benchmarks/Valtuutus.Benchmarks/
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for f in BenchmarkDotNet.Artifacts/results/*-report-full-compressed.json; do
            bencher run \
            --project valtuutus \
            --token "$BENCHER_API_TOKEN" \
            --branch "${{ github.ref_name }}" \
            --testbed ubuntu-latest \
            --threshold-measure latency \
            --threshold-test t_test \
            --threshold-max-sample-size 64 \
            --threshold-upper-boundary 0.99 \
            --thresholds-reset \
            --err \
            --adapter c_sharp_dot_net \
            --file "$f" \
            --github-actions "$GITHUB_TOKEN"
          done
