name: Build and test
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true
permissions:
  checks: write
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: |
            11.x
            10.x
            9.x
            8.x
          include-prerelease: true
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Build
        run: dotnet build Valtuutus.sln --no-incremental
      - name: Test with coverage
        run: dotnet-coverage collect 'dotnet test Valtuutus.sln -c Release --logger:"trx;LogFilePrefix=testResults"' -f cobertura -o 'coverage.xml' -s coverage.runsettings
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: cobertura
          file: coverage.xml
      - name: Upload Test Result Files
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.24.0
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"
