name: Build and test
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
        
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true        
permissions:
  checks: write
  pull-requests: write
env:
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_DOTNET_ENABLE_CONCURRENT_EXECUTION: true  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: |
            9.x
            8.x
            7.x
            6.x
      - name: Install dotnet-sonarscanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Install dotnet-coverage
        run: |
          dotnet tool install --global dotnet-coverage
          
      - name: Build the project, run all tests and publish to SonarCloud
        run: |
          dotnet sonarscanner begin \
          /k:"valtuutus_valtuutus" \
          /o:"valtuutus" \
          /d:sonar.token="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build Valtuutus.sln --no-incremental          
          dotnet-coverage collect 'dotnet test Valtuutus.sln -c Release --logger:"trx;LogFilePrefix=testResults"' -f xml  -o 'coverage.xml'
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"
