name: Run Benchmarks

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - dev

concurrency:
  group: benchmarks-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  benchmark_base_branch:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: |
            11.x
            10.x
            9.x
            8.x
          include-prerelease: true
      - name: Run Benchmarks
        run: |
          dotnet run -f net10.0 -c Release --filter '*' --project benchmarks/Valtuutus.Benchmarks/
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v7
        with:
          name: benchmark_results
          path: BenchmarkDotNet.Artifacts/results/*-report-full-compressed.json
      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v7
        with:
          name: event.json
          path: ${{ github.event_path }}
